### ISSUE TITLE
Expose Collection.strategy.*

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#113]
Maybe I'm looking in the wrong place, but I can't see how I can access the Collection.strategy.* constants from outside the library (I am currently working around this by using the literal strings from https://github.com/Kinto/kinto.js/blob/master/src/collection.js#L85-L87).

**Comment by leplatrem** [comment]
Do you mean that you can't import the Collection class ?

Like:
```js
import Collection from "kinto/lib/collection";

console.log(Collection.strategy.SERVER_WINS);
```
I tried this from the [kinto-react-boilerplate](https://github.com/Kinto/kinto-react-boilerplate) code, and it works.
However, I believe we could expose them on the Kinto class if it's more usable *(since no extra import would be required)*.

**Comment by michielbdejong** [comment]
Tried this from the WebIDE console in B2G, but:
````
> import Collection from "kinto/lib/collection";
SyntaxError: modules are not implemented yet
````
:)

**Comment by n1k0** [comment]
Yeah we should expose these as we did for other things, especially for es5 users.

**Comment by n1k0** [comment]
We should probably move these constants to the Kinto object for consistency, eg. `Kinto.strategies.*` (maybe `Kinto.syncStrategies.*`would be even more explicit).
