### ISSUE TITLE
Remove Gecko build

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto.js#1306]
This library was used in Gecko (~ Firefox internals). In [one component](https://searchfox.org/mozilla-esr68/source/services/settings/RemoteSettingsClient.jsm), only a very tiny part was used, since we didn't need both-way sync. In [another component](https://searchfox.org/mozilla-esr68/source/toolkit/components/extensions/ExtensionStorageSync.jsm), we used both-way sync, but it is being modernized and migrated to another tech that matches the rest of the Firefox sync.

This means mainly two things:
* We don't need the Gecko dist anymore
* We won't provide much maintenance efforts from the Mozilla standpoint (ie. me). Note that it's been pretty stable and quiet in the last years.

@dstaley has been doing an amazing amount of work on the repo, and I would be happy to give him the full privileges for the maintenance and releasing if that allows to guarantee the continuity of this library :)

**Comment by dstaley** [comment]
@leplatrem Thank you so much for all the valuable feedback you've given me over the last few months! It's been an absolute delight to work with you, and I do hope you pop in from time to time to give your thoughts. I will always appreciate them!

I've enjoyed working on the TypeScript transition, and would be happy to take over the primary maintenance and release responsibilities for this library and the HTTP client library.

I do have a few quick questions
1. Does this mean that the Gecko build can be removed from both `kinto.js` and `kinto-http.js`?
1. Will Mozilla be contributing to any Kinto projects in an official capacity?
1. If the answer to the above is "No", do you need me to take over on `kinto-admin` as well? (Happy to do that since I was planning on continuing the TypeScript work over there as well!)

In order to be effective in my maintainer duties, I need two things from you:
1. npm permissions for the `kinto.js` package (I already have `kinto-http.js` and `kinto-node-test-server`.) I'm thinking of moving all our JavaScript packages to an npm org, but it'll still be good to have access to the existing packages.
1. Add all of the GitHub org's repos to the admin group (Currently there's only 15 repos in the admin group, and we have 43 repos in total. Alternatively, you can change my role to Owner in the GitHub org, but I really doubt that's necessary since it looks like the admins group has the admin permission over included repos.)

**Comment by leplatrem** [comment]
Thanks Dylan! 

> 1. Does this mean that the Gecko build can be removed from both kinto.js and kinto-http.js?

Only from `kinto.js` for now.
Kinto will remain the core solution of the Remote Settings component in Firefox, and we'll continue to use kinto-http.js for a while.

**Comment by leplatrem** [comment]
Thanks Dylan! 

> 1. Does this mean that the Gecko build can be removed from both kinto.js and kinto-http.js?

Only from `kinto.js` for now.

Kinto will remain the core solution of the Remote Settings component in Firefox, and we'll continue to use kinto-http.js. We'd like to rewrite some stuff in Rust, but this won't happen before long.

> 2. Will Mozilla be contributing to any Kinto projects in an official capacity?

We used to have a whole team working on Kinto at Mozilla. Along the year people left to chase new adventures and I'm now the only one. So, for now, with regards to Kinto, Mozilla == me :) 

> 3. If the answer to the above is "No", do you need me to take over on kinto-admin as well? (Happy to do that since I was planning on continuing the TypeScript work over there as well!)

I don't think that rewriting in TypeScript is the priority on `kinto-admin`. Not that it wouldn't be useful, but there are other stuff to do that could improve UX (eg. bootstrap4, bulk actions, list filtering, prevent double firing, ...)

> 1. npm permissions for the kinto.js package

Done!

> 2. Add all of the GitHub org's repos to the admin group

I added the main missing ones, you should be good. There are plenty of obsolete stuff in the org...

**Comment by dstaley** [comment]
> Only from `kinto.js` for now.

👍 

> I don't think that rewriting in TypeScript is the priority on `kinto-admin`. Not that it wouldn't be useful, but there are other stuff to do that could improve UX (eg. bootstrap4, bulk actions, list filtering, prevent double firing, ...)

Roger that! Once we get the TypeScript version of `kinto.js` published, I might take a look at uplifting the UI to Bootstrap 4, along with some modernization along the way.

> I added the main missing ones, you should be good. There are plenty of obsolete stuff in the org...

It looks like they were added with read-only permissions. Could you update those to admin?

Thank you!
