### ISSUE TITLE
Deleting a collection

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto.js#136]
A live call to the Kinto server to delete a collection.

- [ ] Peform a `DELETE` HTTP operation to remotely drop the collection;
- [ ] On success, drop the local database containing the collection;
- [ ] Update the local collection instance state to reflect it's been deleted, so it's not usable anymore;
- [ ] On error, raise with a convenient error message explaining the situation;
- [ ] Update documentation;
- [ ] Update dist files.

**Comment by n1k0** [comment]
> A live call to the Kinto server to delete a collection.

Do we immediately delete the collection locally as well? Or should we wait for a next call to sync to changes are reflected then?

**Comment by ametaireau** [comment]
My take on this would be to delete the collection locally as well. Since the operation is issued by the client, it would be weird to still have the collection after this.

**Comment by n1k0** [comment]
Sounds good. So the flow would be, perform the DELETE http operation, on success drop the local database containing the collection (as a reminder, each single collection is stored in its own dedicated local db).

I'll update the description accordingly.

**Comment by n1k0** [comment]
Just a note about the confirmation thing:

> We may want to pass a confirm callback to let the developer handle an UX user confirmation.

This should be handled by the UI only if you ask me.

**Comment by ametaireau** [comment]
+1 on this last remark.

**Comment by Natim** [comment]
I agree that we do not want UI things into Kinto.js, however we should add a pluggable way for people to ask confirmation before deletion, maybe they should just call the kinto.js delete_collection after confirmation only.

**Comment by michielbdejong** [comment]
> perform the DELETE http operation, on success drop the local database containing the collection

Not sure if I understand this - shouldn't everything be done in an offline-first way? I mean, I would imagine two methods, one to 'forget' a collection (drop locally but leave remote intact, iiuc that's what the current `Collection#clear` does), and one to 'delete' a collection (drop locally, and on next sync, drop remotely).

> pass a confirm callback to let the developer handle an UX user confirmation

Not sure if I understand this either - presumably, if the developer is clearly informed with big warnings what the difference between 'forgetting' and 'deleting' a collection is, then it's up to the developer to include big warning alerts to the user /before/ calling the Kinto.js method? What is the use, to a developer, of calling a certain method and then getting a confirmation callback from that method you just called from your code?

I probably misunderstood something in both questions. :)

**Comment by n1k0** [comment]
>  shouldn't everything be done in an offline-first way?

You're obviously right. AFAICR our reasoning was mostly driven by complexity handling; managing collection deletion the offline-first way can get *quite* complicated, because this needs to be added as a batch operation and we'd need an ordered journal to avoid silly situations like batching remote additions to a deleted collection and so on… so that would basically mean garbage collection, possibly ordered journalization, which is a tricky topic to say the least.

Dunno what to do here, diverging from a full offline-first strategy sounds bad to me, on the other hand I feel like getting into the journalization thing might slow us down a lot — though if someone has a *simple* solution, I'm all hears here.

**Comment by Natim** [comment]
Actually there is a difference between clearing a collection (removing all its records) and DELETING a collection (removing the collection data as well as its records)

The first one is handled with the offline first way, but the second one is a cross-devices operation that cannot be aknowledge in an offline first fashion, because you want to know for sure about a success or a failure.

**Comment by michielbdejong** [comment]
I see the problem. If client 1 has deleted the collection (but not pushed this change yet), and client 2 then creates a new record, should client 1 then pull that record creation before or after pushing its collection deletion?

Simple alternative 1: Instead of 'delete the collection' would be 'delete all the records in the collection'. Clients can already do this themselves with sync, then list, then delete each record one-by-one.

Simple alternative 2: collection-level operations always win against record-level operations. So then for each collection that was marked for deletion, do the collection deletion first, and then push out the records that were created since.

**Comment by michielbdejong** [comment]
Oh, and collection creation also has to be dealt with, right? What if two clients create the same collection?

**Comment by Natim** [comment]
The creation subject is another issue #134 At the moment, with a POST, the first one return a 201 with the created records, the other one gets a 200 with the previously created record, on a PUT the second call erase the first one.

If the If-None-Match header is set, you've got a 412 with the existing records:

```
$ echo '{"data": {"fingerprint": 1}}' | http PUT https://kinto.dev.mozaws.net/v1/buckets/default/collections/tasks  If-None-Match:'*' --auth natim:
HTTP/1.1 412 Precondition Failed
Access-Control-Expose-Headers: Backoff, Retry-After, Alert, Content-Length
Connection: keep-alive
Content-Length: 182
Content-Type: application/json; charset=UTF-8
Date: Wed, 16 Sep 2015 10:03:06 GMT
ETag: "1442397768853"
Last-Modified: Wed, 16 Sep 2015 10:02:48 GMT
Server: nginx/1.4.6 (Ubuntu)

{
    "code": 412, 
    "details": {
        "existing": {
            "fingerprint": 2, 
            "id": "tasks", 
            "last_modified": 1442397768853
        }
    }, 
    "errno": 114, 
    "error": "Precondition Failed", 
    "message": "Resource was modified meanwhile"
}
```

**Comment by michielbdejong** [comment]
If a client decides to delete the collection and put some new records in place, that's like one batch action saying "replace this collection's content with these new records". That operation can never lead to conflict, since the fresh records you upload are unrelated to the old records with which other clients are still working. It can even be sent without `If-Match` header.

**Comment by Natim** [comment]
> That operation can never lead to conflict

Actually you can have a 403 when trying to create an existing collection if you don't have the permission to do it.

**Comment by michielbdejong** [comment]
Yeah, but I mean versioning conflicts. A 403 is not a versioning conflict. :)

If sending no `If-Match` header is too brute (I agree it's quite brute), and you do want to communicate conflicts of old records, then even journalizing will probably not be enough. Then you maybe even need to keep a pre-deletion instance and a post-deletion instance of the collection, so that the pre-deletion conflicts can be reported in their context. It makes little sense to get an event saying "this conflict happened on a record that once lived in a collection of which we no longer have a local copy". :)

**Comment by michielbdejong** [comment]
Another question is - what will a collection deletion+creation look like to other clients? Will they get a full list of all the old records when they run `this.api.fetchChangesSince`?

**Comment by michielbdejong** [comment]
Alternative 3: For collection-level actions, add `Kinto#create`, `Kinto#delete` and `Kinto#sync` (with SyncResults `created`, `deleted`, `conflicts`, `resolved`, `skipped`, `error`).

That way it's offline-first, and when the developer calls `kinto.sync()`, they can either set `CLIENT_WINS` to be brute, or if they want to play it safe, there are three options:
* after you just deleted a collection, call `Kinto#sync` first before creating a collection with the same name again (actually creating a collection whose deletion is not yet synced could reasonably raise an error)
* delete records one-by-one instead of doing a collection-level delete
* use multiple Kinto instances with different `dbPrefix`; one which is still linked to the old collection before deletion, and one linked to the new collection contents after deletion

**Comment by michielbdejong** [comment]
Sorry for spamming the comments so much here! :D

After having thought about all these options, I agree with your initial proposal. :) So you could add something like `Kinto#deleteRemoteCollection`. It will fail if there is no network connection, so an offline-first app will never do this directly from a user action.

Since `Collection#sync` will already have to deal with the case where the remote collection is gone (maybe it was deleted by another client), I think it's easiest and simplest if `Kinto#deleteRemoteCollection` affects only the remote collection, and has no side-effects on the local data at all.

**Comment by Natim** [comment]
>  affects only the remote collection, and has no side-effects on the local data at all.

I see what you mean, it makes sense. The user can then use Collection.clear() in the success callback of the deletion promise if she wants to.

**Comment by leplatrem** [comment]
I think this can be closed because kinto-client can do it with something like:
```js
collection.api.bucket(collection.bucket).deleteCollection(collection.name)
```

**Comment by n1k0** [comment]
Indeed!
