### ISSUE TITLE
Investigate offline support feature

### ISSUE THREAD

**Issue by ametaireau** [Kinto/kinto.js#140]
While working on [the *ihatemoney* port to Kinto](http://github.com/ametaireau/ireallyhatemoney), I realised that one of the missing feature was the offline support.

I'm proposing here some way to support offline / online detection into Kinto.js, but this is conditioned to the agreement we should have such a feature inside Kinto.js (we might find that it's better to actually have this outside the scope of Kinto.js, and as a separate repository / in the documentation / boilerplate).

There are multiple things to consider about offline support:

## Offline capability

A standard exists in order to detect offline and online capabilities by the browsers. Unfortunately, not all browsers support it natively so far (see http://caniuse.com/#feat=online-status).

It also seems that there is no existing polyfill for this. I've put together [a hack to bring this to the missing ones](https://gist.github.com/ametaireau/21a8b88416fecc691641). We might want to create a separate library for offline support or package it directly in Kinto.js;

## Offline sync strategy

We should decide on a strategy to use in order to support synchronisation related to the offline / online status. For instance, this could be something like this:

- When connected, pull for changes every {period}. This could probably go away once we've got notification support in Kinto;
- When offline, don't try to do the sync;
- When back online (when we receive the event), issue a sync (maybe only if the last one was less than {period})

This could work well with web workers, which could run the sync process in the background.

**Comment by michielbdejong** [comment]
afaik, [`'offline'` and `'online'` events](https://developer.mozilla.org/en/docs/Online_and_offline_events) should be interpreted as `'definitelyoffline'` and `'dontknow'`, respectively. For instance, when connected to a WiFi network, but not logged in to its login wall, or when connected to a WiFi network with no working uplink to the internet, or where DNS is down. I didn't try this recently, but that's what I remember from looking at it a couple of years ago.

Therefore, it may make sense to just ignore these events, and just try to sync, and see what happens. If the browser knows it is offline, then it will probably just make XHR requests fail in the standard way, so if we handle normal XHR failures properly, then I think we cover everything.

Right now, `collection#sync` will reject its promise with `error.request.status === 0` after a 75 second timeout. So room for improvement both in how network errors are communicated back to the app, and in making that timeout a bit lower / more realistic.

I wasn't aware that Kinto proactively tries sync, btw. I thought it was up to the app to call `collection#sync` periodically?

One thing I think would be useful is if the app can see a list of unpushed changes, so that in the UI, you can show this. In fact, it may make more sense if `collection#sync` fulfills its promise with a `syncResults` object containing the list of more detailed per-record error information, instead of rejecting it?

**Comment by n1k0** [comment]
> I wasn't aware that Kinto proactively tries sync, btw. I thought it was up to the app to call collection#sync periodically?

Yes, and I'd personally like to keep it that way (leaving users deciding how they want to handle the situation). The feature @ametaireau describes sounds amazingly useful, though that's a distinct project imho, or at least a snippet to add to the the docs.

**Comment by leplatrem** [comment]
+1 on keeping this appart :)

It could be an interesting contribution to the [kinto react boilerplate](https://github.com/Kinto/kinto-react-boilerplate) though :)
