### ISSUE TITLE
Cannot create; delete; create a record with same id

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#305]
To reproduce:

````js
var k = new Kinto();
k.collection('foo').create({ id: '7e22bc3a-4515-462b-976d-351d9285002f' },
                           { useRecordId: true }).then(() => {
  return k.collection('foo').delete('7e22bc3a-4515-462b-976d-351d9285002f');
}).then(() => {
  return k.collection('foo').create({ id: '7e22bc3a-4515-462b-976d-351d9285002f' },
                                    { useRecordId: true });
});
````

Expected: should work
Actual: ConstraintError

**Comment by n1k0** [comment]
That's because `delete()` deletes records virtually by default. If you replace your delete call by `.delete({id}, {virtual: false})`, it works.

We should probably check for any virtually deleted id matching the provided one in `create()`.

**Comment by michielbdejong** [comment]
Yes, preparing a fix! :)

**Comment by n1k0** [comment]
> We should probably check for any virtually deleted id matching the provided one in create().

Actually no, because that would:

1. have a possibly big impact on performances
2. conflict with the current implementation of transactions in #303 

Basically, an IndexedDB transaction cannot proceed any async code once it's opened or it could be autocommited; preventing so for checking if any virtually deleted exists sharing the provided id. And preloading the whole database wouldn't be an option as well.

So I think the fix is mostly properly documenting this behaviour and update the error message notifying the user it could also be due to an virtual deletion for this id existing in the collection.

**Comment by michielbdejong** [comment]
ok, I was able to work around it in https://github.com/michielbdejong/kinto-chrome/blob/clear-synced/lib/chrome.js#L136-L167 using `includeDeleted: true` and then delete with `virtual: false` if necessary.

**Comment by michielbdejong** [comment]
Sorry, reopening for adding the documentation improvements.
