### ISSUE TITLE
Add support for crawling paginated list of changes

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto.js#355]
Right now we only fetch the first page sent by the server.

Note: this is a limitation when the server defines a `paginate_by` setting.

**Comment by leplatrem** [comment]
related #277

**Comment by leplatrem** [comment]
Now that `client.listRecords()` supports pagination, it just a matter of specifying `pages: Math.Inf` in the parameters during `pullChanges()`

**Comment by MeghaSharma21** [comment]
Is this bug still open, can I take it up?

**Comment by glasserc** [comment]
@MeghaSharma21 Yes, feel free!

**Comment by MeghaSharma21** [comment]
@glasserc Can you help me getting started?

**Comment by glasserc** [comment]
Sure! Do you understand the issue? The problem is that if a server has a `paginate_by` setting, when the client requests the list of changes, it might only get the first page and stop. The fix is that when the client requests the list of changes, it should go to the next page if necessary. As @leplatrem pointed out, the `listRecords()` method from kinto-http.js already supports pagination, so we just need to use it in the right way.

You should start by cloning the repository and making sure you can run the tests and edit the code. You can find tests in `collection_test.js`. You might need to add a new test or update old ones to reflect your updates. Good luck and feel free to ask for help in #kinto on IRC or Slack!
