### ISSUE TITLE
Which methods are re-entrant?

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto.js#446]
It seems like Collection#update and Collection#delete aren't re-entrant, because their access to the database isn't protected within a single transaction. (They do a `get().then(...)`.) Is this correct? Should/can we fix this?

**Comment by Natim** [comment]
To make sure there is a transaction you need to make sure that the ``last_modified`` value from the get is used for the update/delete with in the `If-Match` header.

**Comment by leplatrem** [comment]
> To make sure there is a transaction you need to make sure that the last_modified value from the get is used for the update/delete with in the If-Match header.

This would be for the interaction with the HTTP API. 

In this case, this is about transactions in indexeddb.

> Is this correct? Should/can we fix this?

Yes, you're right, we should fix this. I'll have a look to see if we can.

**Comment by Natim** [comment]
> This would be for the interaction with the HTTP API.
> In this case, this is about transactions in indexeddb.

Oh yes you are right **kinto.js**, sorry for the misunderstanding.

**Comment by leplatrem** [comment]
So... as we discussed in #450, this is not an easy task.

Mainly because of a very strong limitation of IndexedDB which cannot read within a transaction (read is async, and transaction must remain sync).

Since we need to preserve the `last_modified` field - which allows us to publish safely on the server - we cannot virtually delete nor update a record without reading what we have in the store.

One possible solution would be to store the metadata in a separate store for example, so that it remains untouched when updating the records.

**Comment by glasserc** [comment]
That would make it easier to implement atomic `update()` and `delete()` and shift a lot of complexity onto `sync()`. That might be OK; `sync()` is already not re-entrant, and probably can't be because it has to query its database as well as update a bunch of records in its database.

What would we do with the `_status` field? That's the other field that `update()` touches. In my ideal world, we would put a `_status` of `created` if the record didn't already exist, and `updated` if it did. (The current `update()` also tries to preserve a status of `synced` if no real changes are made.) Since its new status depends on its old status, we have to read it in order to update it. I think if we already knew what it was, we could store it to both using one transaction. I think we'll have to change how we store this if we want to behave correctly.
