### ISSUE TITLE
Pass record to custom ID schema

### ISSUE THREAD

**Issue by blarghmatey** [Kinto/kinto.js#632]
I am beginning work on an application where I would like to be able to generate the ID for a record that is computed from other attributes of the record. Looking at the custom ID schema capabilities there doesn't appear to be any way of getting a handle on the record that the ID is generated for inside the `generate` function.

For example, every record will have a `url` attribute and I would like to compute the ID based on the value of that attribute to ensure that there is never a duplicate value entered for that attribute.

Is something like this possible and if not what would I need to do to enable it?

**Comment by leplatrem** [comment]
That sounds like a reasonable use case to me! And would invite you to draft a PR ;)

@glasserc @Natim what do you think?

**Comment by Natim** [comment]
Yes I agree, in the past we did it by forcing the computation of the id before save the record rather than using `generate` for that but it might make sense to do it there. However, what happens when you update the record with a new `url`?

**Comment by blarghmatey** [comment]
That's a valid point that I did not yet consider. I am still very early in the design/execution of this project, so I'm sure there are some cases that I'm not yet considering.

In the event that the URL changes then I think that the behavior should be to delete the old record and create a new one. Alternatively, if there is a different/better way to ensure uniqueness of a field in a record then it might be worth pursuing that instead of/in addition to the id generation.

**Comment by glasserc** [comment]
I agree with @Natim that a record's ID "changing" seems like a bad thing, and I think detecting something like that would require a certain amount of work. (As of this writing, we only ever call `generate()` when a record doesn't have an ID. When would we check if the record's ID needed to be updated?) I guess I'm not opposed to supporting this if we can manage it, but Kinto doesn't really provide any mechanisms for guaranteeing uniqueness apart from ID, and I am hesitant to commit to anything beyond that. Because we don't offer any kind of "move" operation, conflicts become a bit uglier. In particular, if one client updates a record, and the other "moves" it, I'm worried about the possibility of keeping both IDs.

**Comment by blarghmatey** [comment]
So, I've started digging into this and I'm not sure how viable this option will be.

I can easily pass the record to the `generate` function, the problem comes up because of also having to pass the record to the `validate` function which gets called on every invocation of `execute`. For some of the invocations the record is available to pass through, but for functions such as `get`, `getAny`, or `delete` the only value available is the id.

**Comment by glasserc** [comment]
Yes, the `validate` method is meant to just validate the syntax of the `id` field itself. You won't be able to validate that the ID matches the record. I guess your `validate` method would just have to return `true`..

**Comment by blarghmatey** [comment]
Ok, that makes sense. I was under the assumption that it was intended to validate the accuracy, but if it's just for a syntax check then I can work with that. Thank you for the clarification! I will have a PR inbound some time within the next 24H 😄

**Comment by leplatrem** [comment]
Was fixed in https://github.com/Kinto/kinto.js/pull/727
