### ISSUE TITLE
Be able to provide the Collection URL in order to get Kinto.js compatible with Cliquet specific app.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto.js#83]
On my way to build Syncto and after reading the specification document for Kinto integration with Balrog, I think we should extends Kinto to let people choose their collection URL in case it doesn't follow the exact Kinto formalism.

- For the Readinglist server, the collection URL looks like: ``/v1/articles``
- For CSP policy the collection URL may looks like: ``/1/preloaded-sts-pkp``
- For Syncto, the collection URL may looks like: ``/v1/history`` (complete list of collection can be found here: https://docs.services.mozilla.com/storage/apis-1.5.html#collections)

The rest of the protocol is the one Cliquet uses.

The configuration could be something like:

```
  var db = new Kinto({remote: "https://syncto.dev.mozaws.net/v1"});
  var history = db.collection("history", url="/history", use_middlewares=[SyncCrypto]);
```

Or for the readinglist:
```
  var db = new Kinto({remote: "https://readinglist.services.mozilla.com/v1"});
  var history = db.collection("history", url="/articles");
```

**Comment by n1k0** [comment]
```
  var history = db.collection("history", url="/articles");
```

I'd suggest `path` or `endpoint` instead of `url`. Otherwise sounds reasonable.

**Comment by Natim** [comment]
:+1: for path

**Comment by n1k0** [comment]
@Natim what's the status of this, do you still need it?

**Comment by michielbdejong** [comment]
Regarding syntax, we have collection-level options since this morning, so it could be:
````js
var history = db.collection("history", { path: "/articles" });
````

**Comment by n1k0** [comment]
Definitely, I'm just trying to figure out if the feature is still needed :)

**Comment by ametaireau** [comment]
I would love being able to specify the endpoints myself when using Kinto.js, in order to have it compatible with any Cliquet objects.

[Api#endpoints](https://github.com/Kinto/kinto.js/blob/master/src/api.js#L83-L103) factorizes a big chunk of the logic, but not everything. We reference `bucket` in quite a few locations (and especially in the `Collection` class) and I've yet to find how we should make the `Collection` class more pluggable in this regards.

It seems that it would be possible, but at the cost of a re-factoring in order to remove any Kinto concepts from Kinto.js. Since we don't have such use case yet, I wouldn't bother implementing this just now, since it adds complexity to the overall Kinto.js code.

**Comment by n1k0** [comment]
There's room for extracting cliquet-specific logic from api.js and http.js and move it to a dedicated, independant package; Kinto.js would then add kinto-specific api logic in its own api layer. That's a bunch of work, but definitely something on my long-term schedule.

**Comment by Natim** [comment]
We changed Syncto to cope with Kinto.js URL format.

Also each time a new project arrive in the bosom of the storage team, we have to impose the kinto URL format to them even if they have simple use cases (with only one read-only collection)

I think it is a good thing to use Kinto URLs with Kinto.js because we stays future proof also it might seems a bit rigid to force the bucket namespace.

Also I like the idea of being able to use Kinto.js to read the readinglist articles.

**Comment by leplatrem** [comment]
I am closing this since our storage products are now syncto/kinto.
